### ISSUE TITLE
unknown issue with version 2.7.5

### ISSUE THREAD

**Issue by sirpy** [neo-project/neo-cli#168]
I've tried starting a private net with 2.7.5, but unable to get the first transaction of moving NEO from the multisig address to another address.
I started the same network with same protocol.json+config...json for both 2.7.4 and 2.7.5. with 2.7.5 the transaction just keeps staying in pool and is never confirmed.
with 2.7.4 it works as expected.

Eventually I've also tried with neo-privatenet-docker, there when setting the variable to use neo-cli 2.7.5 it doesnt work at all, but i guess that might be a neo-privatenet-docker bug.

**Comment by metachris** [comment]
Encountered the same issue with the CoZ private net https://github.com/CityOfZion/neo-privatenet-docker -- can't get the initial transaction through with neo-python.

**Comment by Ray-77** [comment]
I've also built a private net with 2.7.5 , but it works fine. And I get the NEO successfully.
![1](https://user-images.githubusercontent.com/17636881/40650566-2cf5099e-6366-11e8-8721-fa0e4ecbb8a9.png)

**Comment by Ray-77** [comment]
![default](https://user-images.githubusercontent.com/17636881/40695055-02ea1d7e-63f2-11e8-9b47-0a3f4c610a4a.png)

**Comment by chenzhitong** [comment]
@metachris I met the same problem. After study, the following conclusions are drawn.

1. The transaction sent was normal, no double-spending, and the broadcast was successful, and I was able to find the Tx in the memory pool of consensus nodes, but the Tx was not confirmed. The same problem has been repeated testing for other transactions.

2. Turn off a consensus node and wait for the closed consensus node to become speaker, and then because the speaker is offline, switching views, the transaction is confirmed after switching views.

3. I discovered the problem by using a different version of the Neo.dll test, and the 1th submission as of May 14 was normal and could confirm the transaction. After the 2nd submission of May 14, there was a phenomenon of consensus nodes only generate block but can't confirmed any transactions. I doubt this submit has a problem. https://github.com/neo-project/neo/commit/cb3a4a75854bb218b7b085b7b8bdaff0c69d7e8c

**Comment by Ray-77** [comment]
I've already transfered the NEO to a standard address successfully.

**Comment by erikzhang** [comment]
@jsolman Can you look at this issue? It seems to be caused by this PR. https://github.com/neo-project/neo/pull/225

**Comment by Ray-77** [comment]
Sometimes my transactions  get stuck in unconfirmed for a period of blocks , but they will be confirmed finally.
![default](https://user-images.githubusercontent.com/17636881/40696915-a9604b44-63fa-11e8-8d70-c66c01c1e31e.png)
![default](https://user-images.githubusercontent.com/17636881/40696922-ad00fc76-63fa-11e8-9b2b-5cc9d2bb0d2f.png)

**Comment by Ray-77** [comment]
And  the neo-cli clients often drop the line.

**Comment by chenzhitong** [comment]
@Ray-77 So we have the same conclusion, when your consensus node drop off the line, it's consistent with my 2nd conclusion.

> Turn off a consensus node and wait for the closed consensus node to become speaker, and then because the speaker is offline, switching views, the transaction is confirmed after switching views.

**Comment by jsolman** [comment]
I don’t think this is related to my change. It seems you already striked through thinking it was though anyway, so I’m not planning to look at this issue.
