### ISSUE TITLE
Will the 1024byte new strategy cause the transaction pool to accumulate?

### ISSUE THREAD

**Issue by QingmingZi** [neo-project/neo-cli#301]
Currently 2.9.4, a new strategy is adopted, and transactions over 1024 bytes require additional fees, but almost all clients do not support this process. Then, is the transaction that is not required to be sent to the memory pool, but will not be accepted by the consensus, and the final trading pool will grow indefinitely? The test network has observed 2700+ transaction stacking.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/2bff318d1d1c8c1d055f111ef08eb5743124a6fa/neo/Ledger/Blockchain.cs#L114

The maximum number of transactions in the memory pool is 50,000.

**Comment by QingmingZi** [comment]
ok，It means that if it is over 50,000, it will be squeezed out。

**Comment by QingmingZi** [comment]
If the transaction sent does not meet the new 1024 fee calculation requirements, but the transaction contains utxo, does it mean that these utxo are locked for a long time?

**Comment by jsolman** [comment]
> If the transaction sent does not meet the new 1024 fee calculation requirements, but the transaction contains utxo, does it mean that these utxo are locked for a long time?

Nodes should use the same policy as the consensus nodes, otherwise their memory pool can indeed hold transactions in it's pool. Currently, if not using the same policy, this can indeed lock UTXOs for that node. They won't be locked, for all nodes though, obviously; so talking, to another node with the same policy as consensus nodes will allow the UTXO to be used.

I've had been thinking about support for allowing a higher fee transaction that uses the same UTXO to push out the lower fee transaction, but since UTXO assets are going away in Neo 3.0, I had decided it is not high enough priority.

**Comment by QingmingZi** [comment]
Already know the solution, you need to install the plugin simplepolicy

**Comment by QingmingZi** [comment]
This plugin is only needed when it is described in the documentation as a private chain consensus. It is a bit misleading.

**Comment by jsolman** [comment]
We should probably change the documentation. Or maybe even `SimplePolicyPlugin` should come already installed with `neo-cli`

**Comment by lock9** [comment]
Hi guys, this issue looks solved. I'm closing it.
If you think this was a mistake, please reopen this issue. Thanks.
