### ISSUE TITLE
Add gui for neocli

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo-cli#462]
we can use electron to add gui for neocli

we type "show gui" to open it like "show state" 

and I had wrote a project for it

https://github.com/lightszero/webwindow.netcore

**Comment by lock9** [comment]
Hi @lightszero, I agree we should have a better interface for neo-cli. The only problem that I see in this approach, is that neo-cli is meant to be work on servers. I think we need a TUI for neo-cli.

**Comment by lightszero** [comment]
If neo-cli have a optional GUI，neo-cli can used both server and client.

**Comment by lock9** [comment]
@lightszero  I'm 100% in favor of having UIs, and just like you mentioned, I think we need a UI for the CLI project, however, here are my considerations:
- The CLI is meant to be running on servers, at least in linux, we don't use servers with UI packages
- We can't use a web interface, otherwise, we are exposing our nodes to remote control
- Web interfaces can't be open in the command line
- Neo-cli is just a command line application, all logic is already in neo library. You will find out that there is little to no code in neo-cli that can be reused. I can only think in the "IsAddress()" function, everything else is already in neo-library

I agree that we need a gui for neo-cli, but if it doesn't work in the command line, this is just neo-gui purpose (we can ship them together in our releases)

If we want (we need) a UI for the command line, we actually need a TUI, that is the adequate term for a GUI that works in the command line. 

The options:
- No UI for cli (make neo-gui instead)
- TUI for cli

In my dreams, we have something similar to this:
![image](https://user-images.githubusercontent.com/38396062/65175724-d09d6100-da29-11e9-8d61-e48c3769700d.png)
and this:
![image](https://user-images.githubusercontent.com/38396062/65175965-3853ac00-da2a-11e9-9292-99cd9631b0ac.png)

**Comment by rdgrabowski** [comment]
For a TUI (something similar to NEO•ONE), what would be necessary? A single repository?

**Comment by lock9** [comment]
@rdgrabowski 
2 options:
- Minor improvements in neo-cli (add some text and basic stuff)
- Use a framework like this one: https://github.com/migueldeicaza/gui.cs

**Comment by Ashuaidehao** [comment]
Hi @lightszero, it's a very creative idea to mix neo-cli and neo-gui. But I wonder if we have implemented it, the neo-cli project would be very complex to maintain, and on the other hand, how to release the mixtrue neo-cli?
I assume 2 plans:
- PlanA - release neo-cli with electron dependencies;
- PlanB - release neo-cli without electron dependencies;

For PlanA, the release package would be large and the release process could be complicated since packing a javascript project into a C# project was quite difficult. On the other side, as @lock9 said before, most of neo-cli users run it on  no-UI servers, they can't get any advantages in this release. 

For PlanB, the release process is as it is now. But for users who want to use the electron gui, they need install electron dependencies by themselves, which may cause a bad user experience.

So I think using electron is a very suitable and feasible solution to develop neo3 gui, but mix neo-cli and neo-gui isn't.
If these problems cannot be resolved, I prefer to a standalone neo-gui.

**Comment by lightszero** [comment]
If gui is [optional],It should be install when user type
"show gui" or something in neocli.

if you do not like this,we can try other solution.

- PLAN C
make GUI as a plugin.
all you need to do is copy GUI files to NEOCLI and restart it.
when you got a GUI plugin.
type "show gui" in neocli,you will got a uiwindow
if you donot have that plugin
type "show gui" will got a error.

@Ashuaidehao

**Comment by lightszero** [comment]
@lock9 @rdgrabowski  
TUI looks like so coll.
Maybe we can get a vote and look how many people like it.

**Comment by Ashuaidehao** [comment]
Install "gui" at runtime looks good for me. Do the GUI files mean just "js/css/html" files or "js/css/html" files with electron runtime files?
One more question, if we work as this, how we controll the version with neo-cli and neo-gui? For example, neo-cli update more frequently than neo-gui, some changes may affect neo-gui but some not. I wonder if the release process may be stucked by the slow gui develop progress.

**Comment by lightszero** [comment]
@lock9  @Ashuaidehao 
they had discuss this topic on 
https://github.com/neo-project/neo-gui/issues/302

so Let's talk TUI in here.

**Comment by lock9** [comment]
Yes, I think it is better. Can you create the issue?
