### ISSUE TITLE
neo-cli-win7-x64.zip not run on win server 2008 R2

### ISSUE THREAD

**Issue by QingmingZi** [neo-project/neo-cli#63]
neo-cli-win7-x64.zip 2.4.1 can't run on win server 2008 R2，but  2.3.5 can

**Comment by Ray-77** [comment]
Maybe you need to download and install this  https://www.microsoft.com/zh-cn/download/details.aspx?id=26755 
![1](https://user-images.githubusercontent.com/17636881/36014557-7f3bce2a-0da5-11e8-9b94-d11a53d1e41a.png)

**Comment by kevingwang** [comment]
I have downloaded this pack and installed it, actually my system does not need it, and the problem is still the same.

![neo](https://user-images.githubusercontent.com/36290679/36015246-a4dc693e-0da8-11e8-9fc6-a98b7150940e.PNG)
![neo2](https://user-images.githubusercontent.com/36290679/36015252-aae33498-0da8-11e8-887f-b83b9b2a5a7f.PNG)

**Comment by erikzhang** [comment]
I think this pack is for Windows Server 2008 R2, not 2008.

**Comment by erikzhang** [comment]
I noticed your system version number is 6.0.6002, which means that it is Windows Server 2008, not 2008 R2. Windows Server 2008 R2 is 6.1.
